#!/bin/bash -ex
echo rm -f binaries/*.bin
rm -rf build
mkdir build
BOOT=PCOM3_SERIAL2 BOARD_ID=Pilo MCU=SAMC21J18A SDCARD=SDCARD_DISABLED make mostly_clean



# captor
BOOT=PCOM0_SERIAL1 BOARD_ID=Captor MCU=SAMC21N18A SDCARD=SDCARD_DISABLED make all mostly_clean
BOOT=FTDI BOARD_ID=Captor MCU=SAMC21N18A SDCARD=SDCARD_DISABLED make all mostly_clean
BOOT=PCOM0_SERIAL2 BOARD_ID=Captor MCU=SAMC21N18A SDCARD=SDCARD_DISABLED make all mostly_clean
BOOT=engi BOARD_ID=Captor MCU=SAMC21N18A SDCARD=SDCARD_DISABLED make all mostly_clean




# pilo
BOOT=PCOM3_SERIAL2 BOARD_ID=Pilo MCU=SAMC21J18A SDCARD=SDCARD_DISABLED make all mostly_clean
BOOT=PCOM3_SERIAL1 BOARD_ID=Pilo MCU=SAMC21J18A SDCARD=SDCARD_DISABLED make all mostly_clean

BOOT=FTDI BOARD_ID=Pilo MCU=SAMC21J18A SDCARD=SDCARD_DISABLED make all mostly_clean
BOOT=engi BOARD_ID=Pilo MCU=SAMC21J18A SDCARD=SDCARD_DISABLED make all mostly_clean


BOOT=PCOM3_SERIAL2 BOARD_ID=Pilo MCU=SAMC21J17A SDCARD=SDCARD_DISABLED make all mostly_clean
BOOT=PCOM3_SERIAL2 BOARD_ID=Pilo MCU=SAMC21J16A SDCARD=SDCARD_DISABLED make all mostly_clean


BOOT=FTDI BOARD_ID=Pilo MCU=SAMD21J18A SDCARD=SDCARD_DISABLED make all mostly_clean
BOOT=FTDI BOARD_ID=Pilo MCU=SAML21J18A SDCARD=SDCARD_DISABLED make all mostly_clean
BOOT=FTDI BOARD_ID=Pilo MCU=SAMD20J18A SDCARD=SDCARD_DISABLED make all mostly_clean
#line
BOARD_ID=Line MCU=SAMD21E15A SDCARD=SDCARD_DISABLED make all mostly_clean

BOARD_ID=Line MCU=SAMD21E16A SDCARD=SDCARD_DISABLED make all mostly_clean
BOARD_ID=Line MCU=SAMD21E18A SDCARD=SDCARD_DISABLED make all mostly_clean
BOARD_ID=Line MCU=SAMD21E17A SDCARD=SDCARD_DISABLED make all mostly_clean

BOARD_ID=engi MCU=SAMC21J18A SDCARD=SDCARD_DISABLED make all mostly_clean
BOARD_ID=engi MCU=SAMC21J17A SDCARD=SDCARD_DISABLED make all mostly_clean
BOARD_ID=engi MCU=SAMC21J16A SDCARD=SDCARD_DISABLED make all mostly_clean
BOARD_ID=engi MCU=SAMC21J15A SDCARD=SDCARD_DISABLED make all mostly_clean

BOOT=PCOM3_SERIAL2 BOARD_ID=Pilo MCU=SAMD21J18A SDCARD=SDCARD_DISABLED make all mostly_clean
BOOT=PCOM3_SERIAL2 BOARD_ID=Pilo MCU=SAMD21J17A SDCARD=SDCARD_DISABLED make all mostly_clean
BOOT=PCOM3_SERIAL2 BOARD_ID=Pilo MCU=SAMD21J16A SDCARD=SDCARD_DISABLED make all mostly_clean
BOOT=PCOM3_SERIAL2 BOARD_ID=Pilo MCU=SAMD21J15A SDCARD=SDCARD_DISABLED make all mostly_clean
BOOT=PCOM3_SERIAL2 BOARD_ID=Pilo MCU=SAMD21J14A SDCARD=SDCARD_DISABLED make all mostly_clean


echo BOARD_ID=engi MCU=SAMD21J18A SDCARD=SDCARD_DISABLED make all mostly_clean
echo BOARD_ID=engi MCU=SAMD21J17A SDCARD=SDCARD_DISABLED make all mostly_clean
echo BOARD_ID=engi MCU=SAMD21J16A SDCARD=SDCARD_DISABLED make all mostly_clean

BOOT=PCOM3_SERIAL2 BOARD_ID=Pilo MCU=SAMD20J18 SDCARD=SDCARD_DISABLED make all mostly_clean
BOOT=PCOM3_SERIAL2 BOARD_ID=Pilo MCU=SAMD20J17 SDCARD=SDCARD_DISABLED make all mostly_clean
BOOT=PCOM3_SERIAL2 BOARD_ID=Pilo MCU=SAMD20J16 SDCARD=SDCARD_DISABLED make all mostly_clean

echo BOARD_ID=engi MCU=SAMD20J18 SDCARD=SDCARD_DISABLED make all mostly_clean
echo BOARD_ID=engi MCU=SAMD20J17 SDCARD=SDCARD_DISABLED make all mostly_clean
echo BOARD_ID=engi MCU=SAMD20J16 SDCARD=SDCARD_DISABLED make all mostly_clean
echo BOARD_ID=engi MCU=SAMD20J15 SDCARD=SDCARD_DISABLED make all mostly_clean
echo BOARD_ID=engi MCU=SAMD20J14 SDCARD=SDCARD_DISABLED make all mostly_clean

BOOT=PCOM3_SERIAL2 BOARD_ID=Pilo MCU=SAMC21J18A SDCARD=SDCARD_DISABLED make mostly_clean





mv -v *.bin ./binaries/
rm *.hex
rm *.bin
echo Done building bootloaders!

