#!/bin/bash -ex
rm -rf binaries
mkdir binaries

BOARD_ID=Pilo MCU=SAMC21J18A SDCARD=SDCARD_DISABLED make all 
BOARD_ID=Pilo MCU=SAMC21J17A SDCARD=SDCARD_DISABLED make all 
BOARD_ID=Pilo MCU=SAMC21J16A SDCARD=SDCARD_DISABLED make all 

BOARD_ID=engi MCU=SAMC21J18A SDCARD=SDCARD_DISABLED make all 
BOARD_ID=engi MCU=SAMC21J17A SDCARD=SDCARD_DISABLED make all 
BOARD_ID=engi MCU=SAMC21J16A SDCARD=SDCARD_DISABLED make all 

BOARD_ID=Pilo MCU=SAMD21J18A SDCARD=SDCARD_DISABLED make all 
BOARD_ID=Pilo MCU=SAMD21J17A SDCARD=SDCARD_DISABLED make all 
BOARD_ID=Pilo MCU=SAMD21J16A SDCARD=SDCARD_DISABLED make all 


BOARD_ID=engi MCU=SAMD21J18A SDCARD=SDCARD_DISABLED make all 
BOARD_ID=engi MCU=SAMD21J17A SDCARD=SDCARD_DISABLED make all 
BOARD_ID=engi MCU=SAMD21J16A SDCARD=SDCARD_DISABLED make all 

BOARD_ID=Pilo MCU=SAMD20J18 SDCARD=SDCARD_DISABLED make all 
BOARD_ID=Pilo MCU=SAMD20J17 SDCARD=SDCARD_DISABLED make all 
BOARD_ID=Pilo MCU=SAMD20J16 SDCARD=SDCARD_DISABLED make all 

BOARD_ID=engi MCU=SAMD20J18 SDCARD=SDCARD_DISABLED make all 
BOARD_ID=engi MCU=SAMD20J17 SDCARD=SDCARD_DISABLED make all 
BOARD_ID=engi MCU=SAMD20J16 SDCARD=SDCARD_DISABLED make all 


mv -v *.bin ./binaries/

echo Done building bootloaders!

